// <auto-generated />
using System;
using FitAgenda.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FitAgenda.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FitAgenda.Domain.Models.Agendamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<Guid>("CodigoAluno")
                        .HasColumnType("uuid")
                        .HasColumnName("codigo_aluno");

                    b.Property<Guid>("CodigoAula")
                        .HasColumnType("uuid")
                        .HasColumnName("codigo_aula");

                    b.Property<DateTime>("DataAgendamento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_agendamento");

                    b.HasKey("Id");

                    b.HasIndex("CodigoAula");

                    b.HasIndex("CodigoAluno", "CodigoAula")
                        .IsUnique()
                        .HasDatabaseName("ix_agendamentos_codigo_aluno_codigo_aula");

                    b.ToTable("agendamentos", (string)null);
                });

            modelBuilder.Entity("FitAgenda.Domain.Models.Aluno", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nome");

                    b.Property<int>("TipoPlano")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_plano");

                    b.HasKey("Id");

                    b.ToTable("alunos", (string)null);
                });

            modelBuilder.Entity("FitAgenda.Domain.Models.Aula", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativa")
                        .HasColumnType("boolean")
                        .HasColumnName("ativa");

                    b.Property<int>("CapacidadeMaxima")
                        .HasColumnType("integer")
                        .HasColumnName("capacidade_maxima");

                    b.Property<Guid>("CodigoTipoAula")
                        .HasColumnType("uuid")
                        .HasColumnName("codigo_tipo_aula");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_hora");

                    b.HasKey("Id");

                    b.HasIndex("CodigoTipoAula");

                    b.ToTable("aulas", (string)null);
                });

            modelBuilder.Entity("FitAgenda.Domain.Models.TipoAula", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.ToTable("tipos_aula", (string)null);
                });

            modelBuilder.Entity("FitAgenda.Domain.Models.Agendamento", b =>
                {
                    b.HasOne("FitAgenda.Domain.Models.Aluno", "Aluno")
                        .WithMany("Agendamentos")
                        .HasForeignKey("CodigoAluno")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitAgenda.Domain.Models.Aula", "Aula")
                        .WithMany("Agendamentos")
                        .HasForeignKey("CodigoAula")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aluno");

                    b.Navigation("Aula");
                });

            modelBuilder.Entity("FitAgenda.Domain.Models.Aula", b =>
                {
                    b.HasOne("FitAgenda.Domain.Models.TipoAula", "TipoAula")
                        .WithMany("Aulas")
                        .HasForeignKey("CodigoTipoAula")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoAula");
                });

            modelBuilder.Entity("FitAgenda.Domain.Models.Aluno", b =>
                {
                    b.Navigation("Agendamentos");
                });

            modelBuilder.Entity("FitAgenda.Domain.Models.Aula", b =>
                {
                    b.Navigation("Agendamentos");
                });

            modelBuilder.Entity("FitAgenda.Domain.Models.TipoAula", b =>
                {
                    b.Navigation("Aulas");
                });
#pragma warning restore 612, 618
        }
    }
}
